# Generated by Django 4.2.3 on 2023-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='inappropriate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='not_helpful',
        ),
        migrations.AddField(
            model_name='comment',
            name='feedback',
            field=models.IntegerField(choices=[(0, 'helpful'), (1, 'not helpful'), (2, 'inappropriate')], default=0),
        ),
    ]
